import type { Config } from 'tailwindcss';

const config: Config = {
    content: [
        './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
        './src/components/**/*.{js,ts,jsx,tsx,mdx}',
        './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
        extend: {
            colors: {
                white: '#fff',
                black: '#000',
                gray: '#8e8e8e',
                primary: '#246beb',
                secondary: '#003675',
                point: '#e71825',
                danger: '#eb003b',
                warning: '#ffb724',
                success: '#008a1e',
                information: '#2768ff',
                'primary-5': '#eff5ff',
                'primary-10': '#d3e1fb',
                'primary-20': '#a7c4f7',
                'primary-30': '#7ca6f3',
                'primary-40': '#5089ef',
                'primary-60': '#1d56bc',
                'primary-70': '#16408d',
                'primary-80': '#0e2b5e',
                'primary-90': '#07152f',
                'secondary-5': '#edf1f5',
                'secondary-10': '#cdd7e4',
                'secondary-20': '#b4c4d6',
                'secondary-30': '#99b0cb',
                'secondary-40': '#2a5c96',
                'secondary-60': '#002b5e',
                'secondary-70': '#002046',
                'secondary-80': '#00162f',
                'secondary-90': '#000b17',
                'point-5': '#fdf2f3',
                'point-10': '#fad1d3',
                'point-20': '#f5a3a8',
                'point-30': '#f1747c',
                'point-40': '#ec4651',
                'point-60': '#b9131e',
                'point-70': '#8b0e16',
                'point-80': '#5c0a0f',
                'point-90': '#2e0507',
                'gray-5': '#f8f8f8',
                'gray-10': '#f0f0f0',
                'gray-20': '#e4e4e4',
                'gray-30': '#d8d8d8',
                'gray-40': '#c6c6c6',
                'gray-50': '#8e8e8e',
                'gray-60': '#717171',
                'gray-70': '#555555',
                'gray-80': '#2d2d2d',
                'gray-90': '#1d1d1d',
            },
            fontFamily: {
                base: ['Pretendard GOV', 'sans-serif'],
            },
            fontSize: {
                'display-sm': '4rem',
                'display-md': '5rem',
                'display-lg': '6.6rem',
                'heading-sm': '3.2rem',
                'heading-md': '4rem',
                'heading-lg': '5rem',
                'title-xsm': '1.5rem',
                'title-sm': '1.7rem',
                'title-md': '1.9rem',
                'title-lg': '2.1rem',
                'title-xlg': '2.5rem',
                'title-xxlg': '3.2rem',
                'body-sm': '1.5rem',
                'body-md': '1.7rem',
                'body-lg': '1.9rem',
                'link-sm': '1.5rem',
                'link-md': '1.7rem',
                'link-lg': '1.9rem',
                'detail-sm': '1.3rem',
                'detail-md': '1.5rem',
                'detail-lg': '1.7rem',
                'label-xsm': '1.3rem',
                'label-sm': '1.5rem',
                'label-md': '1.7rem',
                'label-lg': '1.9rem',
            },
            fontWeight: {
                light: 300,
                normal: 400,
                medium: 500,
                bold: 700,
                bolder: 800,
            },
            lineHeight: {
                none: 1,
                base: 1.5,
            },
            borderRadius: {
                '1': '.1rem',
                '2': '.2rem',
                '4': '.4rem',
                '6': '.6rem',
                '8': '.8rem',
                '10': '1rem',
                '12': '1.2rem',
                full: '100%',
            },
            spacing: {
                '0': '0',
                default: '.1rem',
                default2: '.2rem',
                full: '100%',
            },
            boxShadow: {
                base: '2px 2px 2px 0px rgba(0, 0, 0, 0.15)',
            },
            screens: {
                sm: '600px',
                md: '1024px',
                lg: '1920px',
            },
            transitionProperty: {
                base: 'all',
                fade: 'opacity',
                collapse: 'max-height',
                'collapse-width': 'width',
            },
            transitionTimingFunction: {
                base: 'ease-in-out',
                fade: 'linear',
                collapse: 'ease',
            },
            transitionDuration: {
                base: '0.4s',
                fade: '0.4s',
                collapse: '0.4s',
            },
        },
    },
    plugins: [],
};
export default config;
